name: maw-reranker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3
  - numpy=1.24.4
  - scipy=1.11.4
  - scikit-learn=1.3.2
  - matplotlib=3.8.0
  - tqdm=4.66.1
  - pip:
      - torch==2.1.2
      - torchvision==0.16.2
      - transformers==4.37.2
      - datasets==2.17.1
      - peft==0.9.0
      - pyserini==0.21.0
      - ir-datasets==0.5.5
      - ir-measures==0.3.3
      - faiss-cpu==1.7.4
      - wandb==0.15.12
      - python-dotenv==1.0.1
      - openai==1.13.3
      - langchain==0.1.9
      - langchain-community==0.0.24
      - langchain-openai==0.0.8
      - tiktoken==0.5.2
      - tensorflow==2.15.0
