_wandb:
    value:
        cli_version: 0.21.4
        e:
            jjas7zhpsqz1q5czw2s7923ireddx90h:
                apple:
                    ecpuCores: 4
                    gpuCores: 38
                    memoryGb: 32
                    name: Apple M2 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "27917287424"
                codePath: MAW_reranker.py
                codePathLocal: MAW_reranker.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "960389062656"
                email: enverdenizaskin@gmail.com
                executable: /Users/denizaskin/CodeBase/Technical/.venv/bin/python
                host: Denizs-MacBook-Pro.local
                memory:
                    total: "34359738368"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/denizaskin/CodeBase/Technical/MAW_reranker.py
                python: CPython 3.13.1
                root: /Users/denizaskin/CodeBase/Technical
                startedAt: "2025-09-23T06:13:13.273098Z"
                writerId: jjas7zhpsqz1q5czw2s7923ireddx90h
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 98
            "3":
                - 13
                - 16
            "4": 3.13.1
            "5": 0.21.4
            "6": 4.56.1
            "12": 0.21.4
            "13": darwin-arm64
backbone:
    value: mixedbread-ai/mxbai-rerank-xsmall-v1
dataset:
    value: mteb/scidocs-reranking
maw_strength:
    value: 0
use_maw:
    value: false
